[package]
name = "telegram_bot_api"
version = "0.2.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
